from __future__ import annotations

from datetime import datetime, timezone
from html import escape


def format_timestamp(value: object) -> str:
    raw = str(value or "").strip()
    if not raw:
        return "-"
    normalized = raw.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return raw
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).strftime("%b %d, %Y %H:%M UTC")


def render_base_email(*, eyebrow: str, title: str, subtitle: str, fields: list[tuple[str, str]]) -> dict[str, str]:
    safe_title = escape(title)
    safe_subtitle = escape(subtitle)
    safe_eyebrow = escape(eyebrow)
    normalized_fields = [(str(label), str(value)) for label, value in fields]

    rows_html = "".join(
        "<tr>"
        f"<td style=\"padding:10px 14px;vertical-align:top;font:600 12px/1.4 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#667085;text-transform:uppercase;letter-spacing:0.04em;border-top:1px solid #eaecf0;white-space:nowrap;\">{escape(label)}</td>"
        f"<td style=\"padding:10px 14px;vertical-align:top;font:400 14px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#101828;border-top:1px solid #eaecf0;\">{escape(value)}</td>"
        "</tr>"
        for label, value in normalized_fields
    )
    html = (
        "<!doctype html>"
        "<html><body style=\"margin:0;padding:0;background:#f4f4f5;\">"
        "<div style=\"margin:0;padding:32px 16px;\">"
        "<div style=\"max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e4e7ec;border-radius:18px;overflow:hidden;box-shadow:0 8px 30px rgba(16,24,40,0.08);\">"
        "<div style=\"padding:28px 28px 18px;background:linear-gradient(135deg,#101828 0%,#1d2939 100%);\">"
        "<div style=\"font:700 12px/1.2 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:0.08em;text-transform:uppercase;color:#cbd5e1;\">Rheonic</div>"
        f"<div style=\"margin-top:12px;font:600 12px/1.2 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:0.06em;text-transform:uppercase;color:#f59e0b;\">{safe_eyebrow}</div>"
        f"<h1 style=\"margin:10px 0 0;font:700 30px/1.15 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#ffffff;\">{safe_title}</h1>"
        f"<p style=\"margin:14px 0 0;font:400 15px/1.7 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#d0d5dd;\">{safe_subtitle}</p>"
        "</div>"
        "<div style=\"padding:20px 28px 28px;\">"
        "<table style=\"width:100%;border-collapse:collapse;border-spacing:0;background:#fcfcfd;border:1px solid #eaecf0;border-radius:14px;overflow:hidden;\">"
        f"{rows_html}"
        "</table>"
        "<p style=\"margin:20px 0 0;font:400 13px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#667085;\">"
        "This alert was generated by Rheonic because your project has notifications enabled."
        "</p>"
        "</div>"
        "</div>"
        "</div>"
        "</body></html>"
    )

    text_lines = [f"Rheonic {eyebrow}", title, subtitle, ""]
    text_lines.extend(f"{label}: {value}" for label, value in normalized_fields)
    text = "\n".join(text_lines)
    return {"html": html, "text": text}
