name: rheonic_prod_logs

services:
  promtail:
    image: grafana/promtail:3.0.0
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    environment:
      LOKI_PUSH_URL: ${LOKI_PUSH_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_API_KEY: ${LOKI_API_KEY}
    volumes:
      - ./promtail-config.prod.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail-positions:/tmp
    restart: unless-stopped

volumes:
  promtail-positions:
    name: rheonic_prod_promtail_positions
