export const frontendConfig = {
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000",
  dashboardSelectedProjectStorageKey: "selected_project_id",
  authTokenStorageKey: "rheonic_token",
  authRefreshTokenStorageKey: "rheonic_refresh_token",
  authUserStorageKey: "rheonic_user",
  dashboardMaxSeriesPoints: 60,
  dashboardClockTickMs: 1000,
  dashboardProtectStatsPollMs: 2000,
  dashboardMetricsPollMs: 2000,
  dashboardIncidentsPollMs: 5000,
  dashboardNameMaxLength: 80,
  dashboardNamePattern: "^[A-Za-z0-9 _.-]+$",
  protectDefaultDecisionTimeoutMs: 100,
} as const;
